-- Migrate fa_asset.RECEIVE_YMD / USE_START_YMD to CHAR(8) yyyyMMdd
-- Run once on each company database before deploying updated SP/API.

UPDATE fa_asset
SET RECEIVE_YMD = DATE_FORMAT(RECEIVE_YMD, '%Y%m%d')
WHERE RECEIVE_YMD IS NOT NULL
  AND RECEIVE_YMD NOT REGEXP '^[0-9]{8}$';

UPDATE fa_asset
SET RECEIVE_YMD = REPLACE(REPLACE(TRIM(RECEIVE_YMD), '-', ''), '/', '')
WHERE RECEIVE_YMD IS NOT NULL
  AND RECEIVE_YMD NOT REGEXP '^[0-9]{8}$'
  AND LENGTH(REPLACE(REPLACE(TRIM(RECEIVE_YMD), '-', ''), '/', '')) = 8;

UPDATE fa_asset
SET USE_START_YMD = DATE_FORMAT(USE_START_YMD, '%Y%m%d')
WHERE USE_START_YMD IS NOT NULL
  AND USE_START_YMD NOT REGEXP '^[0-9]{8}$';

UPDATE fa_asset
SET USE_START_YMD = REPLACE(REPLACE(TRIM(USE_START_YMD), '-', ''), '/', '')
WHERE USE_START_YMD IS NOT NULL
  AND USE_START_YMD NOT REGEXP '^[0-9]{8}$'
  AND LENGTH(REPLACE(REPLACE(TRIM(USE_START_YMD), '-', ''), '/', '')) = 8;

ALTER TABLE fa_asset
    MODIFY COLUMN RECEIVE_YMD CHAR(8) NULL COMMENT 'Ngay tiep nhan yyyyMMdd',
    MODIFY COLUMN USE_START_YMD CHAR(8) NOT NULL COMMENT 'Ngay su dung yyyyMMdd';
