namespace API_AMNOTE_WEB.Models
{
    public static class EInvoiceDeclarationMapper
    {
        public static EInvoiceDeclarationDto ToDto(EInvoiceDeclarationInfo entity)
        {
            return new EInvoiceDeclarationDto
            {
                TKHAI_ID = entity.TKHAI_ID,
                COMPANY_CD = entity.COMPANY_CD,
                PBAN = entity.PBAN,
                MSO = entity.MSO,
                TEN = entity.TEN,
                HTHUC = entity.HTHUC,
                TNNT = entity.TNNT,
                MST = entity.MST,
                CQTQLY = entity.CQTQLY,
                MCQTQLY = entity.MCQTQLY,
                TNDDPLUAT = entity.TNDDPLUAT,
                DTDDPLUAT = entity.DTDDPLUAT,
                CCCDAN = entity.CCCDAN,
                SHCHIEU = entity.SHCHIEU,
                MQTNDDPLUAT = entity.MQTNDDPLUAT,
                QTICH = entity.QTICH,
                NSDDPLUAT = entity.NSDDPLUAT,
                GTINH = entity.GTINH,
                DCLHE = entity.DCLHE,
                DCTDTU = entity.DCTDTU,
                NLHE = entity.NLHE,
                DTLHE = entity.DTLHE,
                DDANH = entity.DDANH,
                NLAP = entity.NLAP,
                CMA = entity.CMA,
                CMTMTTIEN = entity.CMTMTTIEN,
                KCMTMTTIEN = entity.KCMTMTTIEN,
                KCMA = entity.KCMA,
                NNTDBKKHAN = entity.NNTDBKKHAN,
                NNTKTDNUBND = entity.NNTKTDNUBND,
                CQXLTSCONG = entity.CQXLTSCONG,
                CDLTTDCQT = entity.CDLTTDCQT,
                CDLQTCTN = entity.CDLQTCTN,
                TCNNGOAI = entity.TCNNGOAI,
                CDDU = entity.CDDU,
                CDLTHDTHU = entity.CDLTHDTHU,
                CBTHOP = entity.CBTHOP,
                CTTCTGDICH = entity.CTTCTGDICH,
                HDGTGT = entity.HDGTGT,
                HDGTGTTHBLAI = entity.HDGTGTTHBLAI,
                HDBHANG = entity.HDBHANG,
                HDBHTHBLAI = entity.HDBHTHBLAI,
                HDTMAI = entity.HDTMAI,
                HDNCCNNGOAI = entity.HDNCCNNGOAI,
                HDBTSCONG = entity.HDBTSCONG,
                HDBHDTQGIA = entity.HDBHDTQGIA,
                HDKHAC = entity.HDKHAC,
                CTU = entity.CTU,
                MGDDTU = entity.MGDDTU,
                MTDIEP = entity.MTDIEP,
                XML = entity.XML,
                IS_SIGNED = entity.IS_SIGNED,
                CQT_STATUS = entity.CQT_STATUS,
                MCCQT = entity.MCCQT,
                ERROR_MESSAGE = entity.ERROR_MESSAGE,
                ISDEL = entity.ISDEL,
                DETAILS = entity.DETAILS.Select(ToDetailDto).ToList()
            };
        }

        public static EInvoiceDeclarationDetailDto ToDetailDto(EInvoiceDeclarationDetail entity)
        {
            return new EInvoiceDeclarationDetailDto
            {
                DETAIL_ID = entity.DETAIL_ID,
                TKHAI_ID = entity.TKHAI_ID,
                COMPANY_CD = entity.COMPANY_CD,
                DETAIL_TYPE = entity.DETAIL_TYPE,
                STT = entity.STT,
                TTCHUC = entity.TTCHUC,
                SERI = entity.SERI,
                CTS_HTHUC = entity.CTS_HTHUC,
                TTCGP = entity.TTCGP,
                MSTTCGP = entity.MSTTCGP,
                TTCTN = entity.TTCTN,
                MSTTCTN = entity.MSTTCTN,
                TDVHTPT = entity.TDVHTPT,
                MSTDVHTPT = entity.MSTDVHTPT,
                TDVI = entity.TDVI,
                MSTDUQ = entity.MSTDUQ,
                HDBRMVAO = entity.HDBRMVAO,
                TDLHDTNGAY = entity.TDLHDTNGAY,
                TDLHDDNGAY = entity.TDLHDDNGAY,
                TGUQTNGAY = entity.TGUQTNGAY,
                TGUQDNGAY = entity.TGUQDNGAY,
                TLHDON = entity.TLHDON,
                KHMSHDON = entity.KHMSHDON,
                KHHDON = entity.KHHDON,
                TENDKTH = entity.TENDKTH,
                MSTDKTH = entity.MSTDKTH,
                MDICH = entity.MDICH,
                TNGAY = entity.TNGAY,
                DNGAY = entity.DNGAY,
                GCHU = entity.GCHU,
                RAW_DETAIL_XML = entity.RAW_DETAIL_XML,
                ISDEL = entity.ISDEL
            };
        }

        public static EInvoiceDeclarationInfo ToEntity(EInvoiceDeclarationSaveRequest request, string companyCd)
        {
            return new EInvoiceDeclarationInfo
            {
                TKHAI_ID = request.TKHAI_ID,
                COMPANY_CD = companyCd,
                MSO = request.MSO,
                TEN = request.TEN,
                HTHUC = request.HTHUC,
                TNNT = request.TNNT,
                MST = request.MST,
                CQTQLY = request.CQTQLY,
                MCQTQLY = request.MCQTQLY,
                TNDDPLUAT = request.TNDDPLUAT,
                DTDDPLUAT = request.DTDDPLUAT,
                CCCDAN = request.CCCDAN,
                SHCHIEU = request.SHCHIEU,
                MQTNDDPLUAT = request.MQTNDDPLUAT,
                QTICH = request.QTICH,
                NSDDPLUAT = request.NSDDPLUAT,
                GTINH = request.GTINH,
                DCLHE = request.DCLHE,
                DCTDTU = request.DCTDTU,
                NLHE = request.NLHE,
                DTLHE = request.DTLHE,
                DDANH = request.DDANH,
                NLAP = request.NLAP,
                CMA = request.CMA,
                CMTMTTIEN = request.CMTMTTIEN,
                KCMTMTTIEN = request.KCMTMTTIEN,
                KCMA = request.KCMA,
                NNTDBKKHAN = request.NNTDBKKHAN,
                NNTKTDNUBND = request.NNTKTDNUBND,
                CQXLTSCONG = request.CQXLTSCONG,
                CDLTTDCQT = request.CDLTTDCQT,
                CDLQTCTN = request.CDLQTCTN,
                TCNNGOAI = request.TCNNGOAI,
                CDDU = request.CDDU,
                CDLTHDTHU = request.CDLTHDTHU,
                CBTHOP = request.CBTHOP,
                CTTCTGDICH = request.CTTCTGDICH,
                HDGTGT = request.HDGTGT,
                HDGTGTTHBLAI = request.HDGTGTTHBLAI,
                HDBHANG = request.HDBHANG,
                HDBHTHBLAI = request.HDBHTHBLAI,
                HDTMAI = request.HDTMAI,
                HDNCCNNGOAI = request.HDNCCNNGOAI,
                HDBTSCONG = request.HDBTSCONG,
                HDBHDTQGIA = request.HDBHDTQGIA,
                HDKHAC = request.HDKHAC,
                CTU = request.CTU,
                XML = request.XML,
                IS_SIGNED = request.IS_SIGNED,
                ERROR_MESSAGE = request.ERROR_MESSAGE,
                ISDEL = request.ISDEL,
                DETAILS = request.DETAILS.Select(x => ToDetailEntity(x, companyCd, request.TKHAI_ID)).ToList()
            };
        }

        public static EInvoiceDeclarationDetail ToDetailEntity(EInvoiceDeclarationDetailDto request, string companyCd, long tkhaiId)
        {
            return new EInvoiceDeclarationDetail
            {
                DETAIL_ID = request.DETAIL_ID,
                TKHAI_ID = tkhaiId,
                COMPANY_CD = companyCd,
                DETAIL_TYPE = request.DETAIL_TYPE,
                STT = request.STT,
                TTCHUC = request.TTCHUC,
                SERI = request.SERI,
                CTS_HTHUC = request.CTS_HTHUC,
                TTCGP = request.TTCGP,
                MSTTCGP = request.MSTTCGP,
                TTCTN = request.TTCTN,
                MSTTCTN = request.MSTTCTN,
                TDVHTPT = request.TDVHTPT,
                MSTDVHTPT = request.MSTDVHTPT,
                TDVI = request.TDVI,
                MSTDUQ = request.MSTDUQ,
                HDBRMVAO = request.HDBRMVAO,
                TDLHDTNGAY = request.TDLHDTNGAY,
                TDLHDDNGAY = request.TDLHDDNGAY,
                TGUQTNGAY = request.TGUQTNGAY,
                TGUQDNGAY = request.TGUQDNGAY,
                TLHDON = request.TLHDON,
                KHMSHDON = request.KHMSHDON,
                KHHDON = request.KHHDON,
                TENDKTH = request.TENDKTH,
                MSTDKTH = request.MSTDKTH,
                MDICH = request.MDICH,
                TNGAY = request.TNGAY,
                DNGAY = request.DNGAY,
                GCHU = request.GCHU,
                RAW_DETAIL_XML = request.RAW_DETAIL_XML,
                ISDEL = request.ISDEL
            };
        }
    }
}
